[project]
name = "audio-analysis"
version = "0.1.0"
description = "A Python project for analyzing audio files and extracting relevant features."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
